name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci-checks.yml

  docker:
    name: Docker
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/docker-publish.yml
    with:
      kind: Dev
      push: true
      tags: ghcr.io/yeongaori/noraegaori:dev
